/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package neuronas;

import java.awt.Color;

/**
 *
 * @author Leo
 */
public class neuronasNum extends javax.swing.JFrame {
    double w81=1, w82=1, w83=1, w84=1, w85=1, w86=1, w87=1,w812=1,
        w91=1, w92=1, w93=1, w94=1, w95=1, w96=1, w97=1,w912=1,
        w101=1, w102=1, w103=1, w104=1, w105=1, w106=1, w107=1,w1012=1,
        w111=1, w112=1, w113=1, w114=1, w115=1, w116=1, w117=1,w1112=1,
        
        w138=1, w139=1,w1310=1,w1311=1,w1317=1,
        w148=1, w149=1,w1410=1,w1411=1,w1417=1,
        w158=1, w159=1,w1510=1,w1511=1,w1517=1,
        w168=1, w169=1,w1610=1,w1611=1,w1617=1;
    int x1=0, x2=0, x3=0, x4=0, x5=0, x6=0, x7=0;
    int numBin1=0, numBin2=0, numBin3=0, numBin4=0;
    /**
     * Creates new form neuronasNum
     */
    public neuronasNum() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        text2 = new javax.swing.JTextField();
        text4 = new javax.swing.JTextField();
        text1 = new javax.swing.JTextField();
        text3 = new javax.swing.JTextField();
        text5 = new javax.swing.JTextField();
        text6 = new javax.swing.JTextField();
        text7 = new javax.swing.JTextField();
        rb1 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        rb3 = new javax.swing.JRadioButton();
        rb4 = new javax.swing.JRadioButton();
        rb5 = new javax.swing.JRadioButton();
        rb6 = new javax.swing.JRadioButton();
        rb7 = new javax.swing.JRadioButton();
        rb8 = new javax.swing.JRadioButton();
        rb9 = new javax.swing.JRadioButton();
        rb0 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(102, 153, 255));

        text2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text2ActionPerformed(evt);
            }
        });

        text4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text4ActionPerformed(evt);
            }
        });

        text1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text1ActionPerformed(evt);
            }
        });

        text3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text3ActionPerformed(evt);
            }
        });

        text5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text5ActionPerformed(evt);
            }
        });

        text6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text6ActionPerformed(evt);
            }
        });

        text7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text7ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rb1);
        rb1.setText("1");
        rb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rb2);
        rb2.setText("2");
        rb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rb3);
        rb3.setText("3");
        rb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rb4);
        rb4.setText("4");
        rb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb4ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rb5);
        rb5.setText("5");
        rb5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb5ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rb6);
        rb6.setText("6");
        rb6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb6ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rb7);
        rb7.setText("7");
        rb7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb7ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rb8);
        rb8.setText("8");
        rb8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb8ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rb9);
        rb9.setText("9");
        rb9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb9ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rb0);
        rb0.setText("0");
        rb0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb0ActionPerformed(evt);
            }
        });

        jLabel1.setText("Seleccione el número");

        jLabel2.setText("que desea refleja en el Led");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(text6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(text5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(text7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(text3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(text2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(text4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(30, 30, 30))
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rb5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rb6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rb7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rb8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rb9))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rb0)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rb1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rb2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rb3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rb4)))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(text2, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text4, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(text5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text6, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rb1)
                            .addComponent(rb2)
                            .addComponent(rb3)
                            .addComponent(rb4)
                            .addComponent(rb0))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rb5)
                            .addComponent(rb6)
                            .addComponent(rb9)
                            .addComponent(rb7)
                            .addComponent(rb8))))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text2ActionPerformed

    private void text4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text4ActionPerformed

    private void text1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text1ActionPerformed

    private void text3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text3ActionPerformed

    private void text5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text5ActionPerformed

    private void text6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text6ActionPerformed

    private void text7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text7ActionPerformed

    private void rb0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb0ActionPerformed
    ponerBlanco();
    
    text1.setBackground(Color.red);
    text2.setBackground(Color.red);
    text3.setBackground(Color.red);
    text5.setBackground(Color.red);
    text6.setBackground(Color.red);
    text7.setBackground(Color.red);
    
    numBin1=0;
    numBin2=0;
    numBin3=0;
    numBin4=0;
    
    capaOculta();
    }//GEN-LAST:event_rb0ActionPerformed

    private void rb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb1ActionPerformed
    ponerBlanco();
    
    text1.setBackground(Color.red);
    text7.setBackground(Color.red);
    
    numBin1=1;
    numBin2=0;
    numBin3=0;
    numBin4=0;
    
    capaOculta();
    }//GEN-LAST:event_rb1ActionPerformed

    private void rb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb2ActionPerformed
    ponerBlanco();
    
    text1.setBackground(Color.red);
    text2.setBackground(Color.red);
    text4.setBackground(Color.red);
    text5.setBackground(Color.red);
    text6.setBackground(Color.red);
    
    numBin1=0;
    numBin2=1;
    numBin3=0;
    numBin4=0;
    
    capaOculta();
    }//GEN-LAST:event_rb2ActionPerformed

    private void rb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb3ActionPerformed
    ponerBlanco();
    
    text1.setBackground(Color.red);
    text2.setBackground(Color.red);
    text4.setBackground(Color.red);
    text6.setBackground(Color.red);
    text7.setBackground(Color.red);
    
    numBin1=1;
    numBin2=1;
    numBin3=0;
    numBin4=0;
    
    capaOculta();
    }//GEN-LAST:event_rb3ActionPerformed

    private void rb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb4ActionPerformed
    ponerBlanco();
    
    text1.setBackground(Color.red);
    text3.setBackground(Color.red);
    text4.setBackground(Color.red);
    text7.setBackground(Color.red);
    
    numBin1=0;
    numBin2=0;
    numBin3=1;
    numBin4=0;
    
    capaOculta();
    }//GEN-LAST:event_rb4ActionPerformed

    private void rb5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb5ActionPerformed
    ponerBlanco();
    
    text2.setBackground(Color.red);
    text3.setBackground(Color.red);
    text4.setBackground(Color.red);
    text6.setBackground(Color.red);
    text7.setBackground(Color.red);
    
    numBin1=1;
    numBin2=0;
    numBin3=1;
    numBin4=0;
    
    capaOculta();
    }//GEN-LAST:event_rb5ActionPerformed

    private void rb6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb6ActionPerformed
    ponerBlanco();
    
    text2.setBackground(Color.red);
    text3.setBackground(Color.red);
    text4.setBackground(Color.red);
    text5.setBackground(Color.red);
    text6.setBackground(Color.red);
    text7.setBackground(Color.red);
    
    numBin1=0;
    numBin2=1;
    numBin3=1;
    numBin4=0;
    
    capaOculta();
    }//GEN-LAST:event_rb6ActionPerformed

    private void rb7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb7ActionPerformed
    ponerBlanco();
    
    text1.setBackground(Color.red);
    text2.setBackground(Color.red);
    text7.setBackground(Color.red);
    
    numBin1=1;
    numBin2=1;
    numBin3=1;
    numBin4=0;
    
    capaOculta();
    }//GEN-LAST:event_rb7ActionPerformed

    private void rb8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb8ActionPerformed
  
    
    ponerBlanco();
    
    text1.setBackground(Color.red);
    text2.setBackground(Color.red);
    text3.setBackground(Color.red);
    text4.setBackground(Color.red);
    text5.setBackground(Color.red);
    text6.setBackground(Color.red);
    text7.setBackground(Color.red);
    
    numBin1=0;
    numBin2=0;
    numBin3=0;
    numBin4=1;
    
    capaOculta();
    }//GEN-LAST:event_rb8ActionPerformed

    private void rb9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb9ActionPerformed
    ponerBlanco();
    
    text1.setBackground(Color.red);
    text2.setBackground(Color.red);
    text3.setBackground(Color.red);
    text4.setBackground(Color.red);
    text6.setBackground(Color.red);
    text7.setBackground(Color.red);
    
    numBin1=1;
    numBin2=0;
    numBin3=0;
    numBin4=1;
    
    capaOculta();
    }//GEN-LAST:event_rb9ActionPerformed
    
    public void ponerBlanco(){
    text1.setBackground(Color.WHITE);
    text2.setBackground(Color.WHITE);
    text3.setBackground(Color.WHITE);
    text4.setBackground(Color.WHITE);
    text5.setBackground(Color.WHITE);
    text6.setBackground(Color.WHITE);
    text7.setBackground(Color.WHITE);
    }
    
    public void capaOculta(){
         for(int i=1; i<10001; i++){
        System.out.println("----------------------- " + i+"---------------------");
        double n8=0, n9=0, n10=0, n11=0;
        double z8=0, z9=0, z10=0, z11=0;
        if (text1.getBackground() == Color.red) {
            x1=1;
        }
        if (text2.getBackground() == Color.red) {
            x2=1;
        }
        if (text3.getBackground() == Color.red) {
            x3=1;
        }
        if (text4.getBackground() == Color.red) {
            x4=1;
        }
        if (text5.getBackground() == Color.red) {
            x5=1;
        }
        if (text6.getBackground() == Color.red) {
            x6=1;
        }
        if (text7.getBackground() == Color.red) {
            x7=1;
        }
        
        n8=(x1*w81)+(x2*w82)+(x3*w83)+(x4*w84)+(x5*w85)+(x6*w86)+(x7*w87)+(1*w812);
        n9=(x1*w91)+(x2*w92)+(x3*w93)+(x4*w94)+(x5*w95)+(x6*w96)+(x7*w97)+(1*w912);
        n10=(x1*w101)+(x2*w102)+(x3*w103)+(x4*w104)+(x5*w105)+(x6*w106)+(x7*w107)+(1*w1012);
        n11=(x1*w111)+(x2*w112)+(x3*w113)+(x4*w114)+(x5*w115)+(x6*w116)+(x7*w117)+(1*w1112);
        
        z8=1/(1+Math.pow(2.71828182846,-n8));
        z9=1/(1+Math.pow(2.71828182846,-n9));
        z10=1/(1+Math.pow(2.71828182846,-n10));
        z11=1/(1+Math.pow(2.71828182846,-n11));
        
        System.out.println("Capa oculta \n resultado n8:  "+n8+"    resultado z8:  "+z8+
                           "\nresultado n9:  "+n9+"    resultado z9:  "+z9+
                           "\nresultado n10: "+n10+"   resultado z10: "+z10+
                           "\nresultado n11: "+n11+"   resultado z11: "+z11);
        capaSalida(z8, z9, z10, z11);
        
    }
    }
    public void capaSalida(double z8, double z9, double z10, double z11){
        double z13=0, z14=0, z15=0, z16=0;
        double n13=0, n14=0, n15=0, n16=0;
        double resultN=0, resultZ=0;
        
        n13=(z8*w138)+(z9*w139)+(z10*w1310)+(z11*w1311)+1*w1317;
        n14=(z8*w148)+(z9*w149)+(z10*w1410)+(z11*w1411)+1*w1417;
        n15=(z8*w158)+(z9*w159)+(z10*w1510)+(z11*w1511)+1*w1517;
        n16=(z8*w168)+(z9*w169)+(z10*w1610)+(z11*w1611)+1*w1617;
        
        z13=1/(1+Math.pow(2.71828182846,-n13));
        z14=1/(1+Math.pow(2.71828182846,-n14));
        z15=1/(1+Math.pow(2.71828182846,-n15));
        z16=1/(1+Math.pow(2.71828182846,-n16));
        
        System.out.println("\n\nCapa de salida "
                        + "\nresultado n8:  "+n13+"    resultado z13:  "+z13
                        + "\nresultado n9:  "+n14+"    resultado z14:  "+z14
                        + "\nresultado n10: "+n15+"   resultado z15: "+z15
                        +"\nresultado n11: "+n16+"   resultado z16: "+z16);
        capaSalidaErrores(z8, z9, z10, z11, z13, z14, z15, z16);
        
    }
    
    public void capaSalidaErrores(double z8, double z9, double z10, double z11, double z13, double z14, double z15, double z16){
        double s13=0, s14=0, s15=0, s16=0;
        s13=z13*(1-z13)*(numBin4-z13);
        s14=z14*(1-z14)*(numBin3-z14);
        s15=z15*(1-z15)*(numBin2-z15);
        s16=z16*(1-z16)*(numBin1-z16);
        
        System.out.println("\n\nCapa de salida errores \nresultado s13:  "+s13+
                           "\nresultado s14:  "+s14+
                           "\nresultado s15: "+s15+
                           "\nresultado s16: "+s16);
        capaOcultaErrores(z8, z9, z10, z11, s13, s14, s15, s16);
        valReajustePesos(z8, z9, z10, z11, s13, s14, s15, s16);
    }
    
    public void capaOcultaErrores(double z8, double z9, double z10, double z11, double s13, double s14, double s15, double s16)
    {
      double s8=0, s9=0, s10=0, s11=0;
      s8= z8*(1-z8)*((w138*s13)+(w148*s14)+(w158*s15)+(w168*s16));  
      s9=z9*(1-z9)*((w139*s13)+(w149*s14)+(w159*s15)+(w169*s16)); 
      s10=z10*(1-z10)*((w1310*s13)+(w1410*s14)+(w1510*s15)+(w1610*s16)); 
      s11=z11*(1-z11)*((w1311*s13)+(w1411*s14)+(w1511*s15)+(w1611*s16)); 
      
           System.out.println("\n\nCapa oculta errores \nresultado s13:  "+s8+
                           "\nresultado s14:  "+s9+
                           "\nresultado s15: "+s10+
                           "\nresultado s16: "+s11);
           ocultaReajustePesos(s8, s9, s10, s11);
    }
    
    public void valReajustePesos(double z8, double z9, double z10, double z11, double s13, double s14, double s15, double s16){
        w138=calReajustePesos(w138, s13, z8);
        w148=calReajustePesos(w148, s14, z8);
        w158=calReajustePesos(w158, s15, z8);
        w168=calReajustePesos(w168, s16, z8);
        
        w139=calReajustePesos(w139, s13, z9);
        w149=calReajustePesos(w149, s14, z9);
        w159=calReajustePesos(w159, s15, z9);
        w169=calReajustePesos(w169, s16, z9);
        
        w1310=calReajustePesos(w1310, s13, z10);
        w1410=calReajustePesos(w1410, s14, z10);
        w1510=calReajustePesos(w1510, s15, z10);
        w1610=calReajustePesos(w1610, s16, z10);
        
        w1311=calReajustePesos(w1311, s13, z11);
        w1411=calReajustePesos(w1411, s14, z11);
        w1511=calReajustePesos(w1511, s15, z11);
        w1611=calReajustePesos(w1611, s16, z11);
        
        w1317=calReajustePesos(w1317, s13, 1);
        w1417=calReajustePesos(w1417, s14, 1);
        w1517=calReajustePesos(w1517, s15, 1);
        w1617=calReajustePesos(w1617, s16, 1);      
    }
    
    public void ocultaReajustePesos(double s8, double s9, double s10, double s11){
        w81=calReajustePesos(w81, s8, x1);
        w82=calReajustePesos(w82, s8, x2);
        w83=calReajustePesos(w83, s8, x3);
        w84=calReajustePesos(w84, s8, x4);
        w85=calReajustePesos(w85, s8, x5);
        w86=calReajustePesos(w86, s8, x6);
        w87=calReajustePesos(w87, s8, x7);
        w812=calReajustePesos(w812, s8, 1);
        
        w91=calReajustePesos(w91, s9, x1);
        w92=calReajustePesos(w92, s9, x2);
        w93=calReajustePesos(w93, s9, x3);
        w94=calReajustePesos(w94, s9, x4);
        w95=calReajustePesos(w95, s9, x5);
        w96=calReajustePesos(w96, s9, x6);
        w97=calReajustePesos(w97, s9, x7);
        w912=calReajustePesos(w912, s9, 1);
        
        w101=calReajustePesos(w101, s10, x1);
        w102=calReajustePesos(w102, s10, x2);
        w103=calReajustePesos(w103, s10, x3);
        w104=calReajustePesos(w104, s10, x4);
        w105=calReajustePesos(w105, s10, x5);
        w106=calReajustePesos(w106, s10, x6);
        w107=calReajustePesos(w107, s10, x7);
        w1012=calReajustePesos(w1012, s10, 1);
        
        w111=calReajustePesos(w111, s11, x1);
        w112=calReajustePesos(w112, s11, x2);
        w113=calReajustePesos(w113, s11, x3);
        w114=calReajustePesos(w114, s11, x4);
        w115=calReajustePesos(w115, s11, x5);
        w116=calReajustePesos(w116, s11, x6);
        w117=calReajustePesos(w117, s11, x7);
        w1112=calReajustePesos(w1112, s11, 1);
        
    /*System.out.print("\033[H\033[2J");
    System.out.flush();*/     
    }
    public double calReajustePesos(double w, double s, double z){
        return w+(1*s*z);
    }

   
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(neuronasNum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(neuronasNum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(neuronasNum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(neuronasNum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new neuronasNum().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton rb0;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JRadioButton rb3;
    private javax.swing.JRadioButton rb4;
    private javax.swing.JRadioButton rb5;
    private javax.swing.JRadioButton rb6;
    private javax.swing.JRadioButton rb7;
    private javax.swing.JRadioButton rb8;
    private javax.swing.JRadioButton rb9;
    private javax.swing.JTextField text1;
    private javax.swing.JTextField text2;
    private javax.swing.JTextField text3;
    private javax.swing.JTextField text4;
    private javax.swing.JTextField text5;
    private javax.swing.JTextField text6;
    private javax.swing.JTextField text7;
    // End of variables declaration//GEN-END:variables
}
